server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eruka7003.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false  #如果为false，则表示自己为注册中心，等别人过来连就好了
    service-url: #监控页面
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
      #  http://localhost:7001/eureka/